on:
  push:
    branches:
      - master

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: takutakahashi/workspace
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=IMAGE_NAME::${IMAGE_NAME}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: takutakahashi
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build:image'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ steps.branch_name.outputs.IMAGE_NAME }}:${{ github.sha }}
 
