name: test
on: [push]
jobs:
  manjaro:
    runs-on: ubuntu-20.04
    container:
      image: 'ghcr.io/takutakahashi/linux-desktop/manjaro'
    steps:
      - uses: actions/checkout@v2
      - run: ./entrypoint.sh manjaro
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./entrypoint.sh ubuntu
  darwin:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./entrypoint.sh darwin
